# Generated by Django 5.0.3 on 2024-09-17 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=100, unique=True)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provider', models.CharField(max_length=100, unique=True)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=0, help_text='Input nominal saldo', max_digits=15)),
                ('tanggal_input', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JenisProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.jenis')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga_modal', models.DecimalField(decimal_places=0, max_digits=15)),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=15)),
                ('jumlah_stok', models.PositiveIntegerField(default=0)),
                ('jenis_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.jenisprovider')),
            ],
        ),
    ]
