# Generated by Django 5.0.3 on 2024-09-17 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jenisprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.jenisprovider')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.produk')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=15)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('pulsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.pulsa')),
            ],
        ),
    ]
